source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '8.0'

target 'DYMRollingBanner_Example', :exclusive => true do
  pod "DYMRollingBanner", :path => "../"
  pod 'SDWebImage', '~> 3.7.3'
end

target 'DYMRollingBanner_Tests', :exclusive => true do
  pod "DYMRollingBanner", :path => "../"

  
end
